
name: 'aw_dbt'
version: '1.0.0'

profile: 'aw_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

packages-install-path: dbt_packages

clean-targets:
  - "target"
  - "dbt_modules"

target-path: "target"
  
models:
  aw_dbt:

    staging:
      +schema: staging  
      +database: aw_database
      materialized: view
    
      intermediate:
      +schema: intermediate
      +database: aw_database
      materialized: view

    marts:
      +schema: marts
      +database: aw_database
      materialized: table

